### ISSUE TITLE
cykdtree install fails on systems (e.g., BlueWaters) where mpi is not OpenMPI or MPICH

### ISSUE THREAD

**Issue by chummels** [cykdtree/cykdtree#12]
When one attempts to install `cykdtree` on BlueWaters with `mpi4py` installed, `cykdtree` fails.  It appears that the issue is with `cykdtree` assuming that the MPI installation is `OpenMPI` or `MPICH`, when BlueWaters uses Intel's MPI implementation.  

```
src/cykdtree> module load bwpy bwpy-mpi
src/cykdtree> pip install --user mpi4py
Requirement already satisfied: mpi4py in /mnt/bwpy/mpi/usr/lib/python3.5/site-packages
src/cykdtree> pip install --user -e .
Obtaining file:///mnt/a/u/sciteam/chummels/src/cykdtree
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/mnt/a/u/sciteam/chummels/src/cykdtree/setup.py", line 76, in <module>
        get_mpi_args('mpic++', '-compile_info', '-link_info') or  # MPICH
      File "/mnt/a/u/sciteam/chummels/src/cykdtree/setup.py", line 49, in get_mpi_args
        compile_args = call_subprocess([mpi_executable, compile_argument])
      File "/mnt/a/u/sciteam/chummels/src/cykdtree/setup.py", line 37, in call_subprocess
        p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE)
      File "/mnt/bwpy/single/usr/lib/python3.5/subprocess.py", line 676, in __init__
        restore_signals, start_new_session)
      File "/mnt/bwpy/single/usr/lib/python3.5/subprocess.py", line 1289, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    PermissionError: [Errno 13] Permission denied

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /mnt/a/u/sciteam/chummels/src/cykdtree/
```

This is not a problem if I uninstall `mpi4py` beforehand.  I'm happy to help debug/patch this if you give me some tips on what to do.  Just wasn't sure how to proceed.

**Comment by chummels** [comment]
Pinging @langmm on this, as suggested by @ngoldbaum .

**Comment by chummels** [comment]
Also, for some context on the compiler environment on Blue Waters.  Looks like everything is linked to `cc`:

https://bluewaters.ncsa.illinois.edu/compiling
